title: whdzera
email: whdzera@gmail.com
description: >- 
  Temukan berbagai tulisan menarik seputar teknologi. Blog ini dibuat sebagai ruang berbagi ide, pengalaman, dan pengetahuan yang bisa bermanfaat untuk siapa saja. Yuk, jelajahi dan temukan sesuatu yang baru di setiap postingannya!
baseurl: ""  
url: ""  
twitter_username: whdzera
github_username: whdzera
linkedin_username: whdzera
youtube_username: whdzera
logo: whdzera
permalink: "/:title.html"
footer: "Created with â¤ by whdzera"
disqus: "rokhimin.disqus"

permalink: /blog/:title

plugins:
  - jekyll-feed

include:
  - _pages
